spring:
    application:
        name: eurekaserver
    security:
        user:
            name: user
            password: user
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false


    instance:
        prefer-ip-address: true
        hostname: eurekaserver
server:
    port: 8762

