eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    prefer-ip-address: true


spring:
  kafka:
    bootstrap-servers: kafka:9092
    streams:
      replication-factor: 1
  security:
    user:
      name: user
      password: user
  datasource:
    url: jdbc:postgresql://postgres:5432/DEVICE
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  topics:
    user:
      topic-name: users
      store-name: users-state-store
    device:
      topic-name: devices
      store-name: device-state-store