eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      replication-factor: 1
    properties:
      metadata.max.age.ms: 30000
      ssl.endpoint.identification.algorithm: ""
    producer:
      properties:
        client.dns.lookup: default
    consumer:
      properties:
        client.dns.lookup: default
  datasource:
    url: jdbc:postgresql://localhost:5432/DEVICE
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: user
      password: user

application:
  topics:
    user:
      topic-name: users
      store-name: users-state-store
    device:
      topic-name: devices
      store-name: device-state-store


  local-service-endpoint:
    user-admin: http://localhost:8083/
    device-admin: http://localhost:8084/